name: TechCrafter
version: 1.0-SNAPSHOT
main: com.techcrafter.Main
api-version: 1.20
commands:
  tech:
    description: دستور اصلی پلاگین
    usage: /<command>
permissions:
  techcrafter.use:
    description: اجازه استفاده از پلاگین
    default: true
