name: TechCrafter
main: com.techcrafter.Main
version: 1.0
api-version: 1.20.1

commands:
  tech:
    description: دستورات اصلی TechCrafter
    usage: /tech <subcommand>
    permission: techcrafter.use

permissions:
  techcrafter.use:
    description: اجازه استفاده از دستورات TechCrafter
    default: true
