name: TechCrafter
main: com.techcrafter.Main
version: 1.0
api-version: 1.20
commands:
  tech:
    description: دستورات اصلی TechCrafter
    usage: /tech <subcommand>
    permission: techcrafter.use
    permission-message: "§cشما اجازه استفاده از این دستور را ندارید."
permissions:
  techcrafter.use:
    description: اجازه استفاده از دستور /tech
    default: true
